export const intransit = ["ordernumber", "APML Remarks", "Remaining kms", "Current Loc.","Origin", "eway number", "eway exp", "gc Number", "Stages", "Vehicle No.", "Order By", "Order days", "Driver no.", "Vehicle type", "Total Distance",  "Ship To Party", "Ship To Address", "expected time ", "gateInTime vs arrivalTime", "departureTime vs gateInTime"]
export const pendingheader = [`orderNumber`, "origin", "shiptoparty", "shiptoaddress", "material", "totalvehicle", "pickupdate", "expecteddeliverydate", "orderby", "mydate", "shplinstructions", "Apml Remarks"]
export const enroutehader = ["Order number", "Origin", "Gc Number", "Vehicle No.", "Total Distance", "Order By", "Order Days ", "Ship To Party", "ship to address", "material", "vehicle type", "expected Pickup Date ", "expected Delivery Date", "SHPL instructions", "Apml Remarks"]
export const Atpickuphader = ["order number", "Origin", "GC Number", "Vehicle No.", "Total Distance", "Remaining Distance", "Order By.", "Order Days", "Ship To Party", "Ship To Address", "Vehicle Type", "expected Delivery time", "SHPL instructions", "At | GI | LS | LE", "Now Vs arrivalTime", "gateInTime vs arrivalTime ", "Load. start Vs gateInTime", "Load.End Vs Load.Start", "APML Remarks"]
export const atunloadingheader = ["order number", "Origin", "GC Number", "Vehicle No.", "Total Distance", "Order By", "Order days", "Ship To Party", "Ship To Address", "Vehicle Type", "Expected Delivery time", "shplinstructions", "At | LS | LE", "Now Vs arrivalTime", "UnLoad. start Vs arrivalTime", "UnLoad.End Vs UnLoad.Start", "Apml Remarks", "Invoice Number", "Invoice Date"]

// map state latlong  */}
export const statelatlong = [
  {
    state: "Andhra Pradesh",
    capital: "Amaravati",
    latitude: 16.5745,
    longitude: 80.3736,
  },
  {
    state: "Arunachal Pradesh",
    capital: "Itanagar",
    latitude: 27.102,
    longitude: 93.692,
  },
  {
    state: "Assam",
    capital: "Dispur",
    latitude: 26.1433,
    longitude: 91.7898,
  },
  {
    state: "Bihar",
    capital: "Patna",
    latitude: 25.5941,
    longitude: 85.1376,
  },
  {
    state: "Chhattisgarh",
    capital: "Raipur",
    latitude: 21.2514,
    longitude: 81.6296,
  },
  {
    state: "Goa",
    capital: "Panaji",
    latitude: 15.4909,
    longitude: 73.8278,
  },
  {
    state: "Gujarat",
    capital: "Gandhinagar",
    latitude: 23.2156,
    longitude: 72.6369,
  },
  {
    state: "Haryana",
    capital: "Chandigarh",
    latitude: 30.7333,
    longitude: 76.7794,
  },
  {
    state: "Himachal Pradesh",
    capital: "Shimla",
    latitude: 31.1048,
    longitude: 77.1734,
  },
  {
    state: "Jharkhand",
    capital: "Ranchi",
    latitude: 23.3441,
    longitude: 85.3096,
  },
  {
    state: "Karnataka",
    capital: "Bengaluru",
    latitude: 12.9716,
    longitude: 77.5946,
  },
  {
    state: "Kerala",
    capital: "Thiruvananthapuram",
    latitude: 8.5241,
    longitude: 76.9366,
  },
  {
    state: "Madhya Pradesh",
    capital: "Bhopal",
    latitude: 23.2599,
    longitude: 77.4126,
  },
  {
    state: "Maharashtra",
    capital: "Mumbai",
    latitude: 19.076,
    longitude: 72.8777,
  },
  {
    state: "Manipur",
    capital: "Imphal",
    latitude: 24.817,
    longitude: 93.9368,
  },
  {
    state: "Meghalaya",
    capital: "Shillong",
    latitude: 25.5788,
    longitude: 91.8933,
  },
  {
    state: "Mizoram",
    capital: "Aizawl",
    latitude: 23.7367,
    longitude: 92.7146,
  },
  {
    state: "Nagaland",
    capital: "Kohima",
    latitude: 25.6747,
    longitude: 94.11,
  },
  {
    state: "Odisha",
    capital: "Bhubaneswar",
    latitude: 20.2961,
    longitude: 85.8245,
  },
  {
    state: "Punjab",
    capital: "Chandigarh",
    latitude: 30.7333,
    longitude: 76.7794,
  },
  {
    state: "Rajasthan",
    capital: "Jaipur",
    latitude: 26.9124,
    longitude: 75.7873,
  },
  {
    state: "Sikkim",
    capital: "Gangtok",
    latitude: 27.3389,
    longitude: 88.6065,
  },
  {
    state: "Tamil Nadu",
    capital: "Chennai",
    latitude: 13.0827,
    longitude: 80.2707,
  },
  {
    state: "Telangana",
    capital: "Hyderabad",
    latitude: 17.385,
    longitude: 78.4867,
  },
  {
    state: "Tripura",
    capital: "Agartala",
    latitude: 23.8315,
    longitude: 91.2868,
  },
  {
    state: "Uttar Pradesh",
    capital: "Lucknow",
    latitude: 26.8467,
    longitude: 80.9462,
  },
  {
    state: "Uttarakhand",
    capital: "Dehradun",
    latitude: 30.3165,
    longitude: 78.0322,
  },
  {
    state: "West Bengal",
    capital: "Kolkata",
    latitude: 22.5726,
    longitude: 88.3639,
  },
];

 export const city =[
  "Agartala","Agra","Ahmedabad","Ahmednagar","Alwar","Ambala","Anand","Anantapur","Anantnag","Angul","Anjar","Ankleshwar","Anpara","Aurangabad",
"Baddi","Bahadurgarh","Bahour","Baihata","Ballabhgarh","Bangarupalem","Baramati","Barbil","Bardez","Bareilly","Barwani","Bathinda","Bawal",
"Belgaum","Bengaluru","Beri","Betul","Bharuch","Bhilai","Bhilwara","Bhind","Bhiwadi","Bhiwandi","Bhopal","Bhubaneswar","Bilaspur","Bongaon","Buldhana","Burgul",
"Chalakudy","Chandigarh","Chandrapur","Chengalpattu","Chennai","Chittoor","Coimbatore","Dabhel","Dadra","Daman","Dandeli","Davanagere","Dehradun","Delhi","Dewas",
"Dhar","Dharuhera",
"Dharwad",
"Dhule",
"East Godavari",
"East Singhbhum",
"Ernakulam",
"Etah",
"Faridabad",
"Gadarpur",
"Gandhidham",
"Gangtok",
"Gauribidanur",
"Gautam Buddh Nagar",
"Ghaziabad",
"Goa",
"Gondal",
"Gorakhpur",
"Greater Noida",
"Gurugram",
"Guwahati",
"Gwalior",
"Haldwani",
"Haridwar",
"Hirakud",
"Hisar",
"Hosapete",
"Hosur",
"Hubli",
"Hyderabad",
"Indore",
"J.P. Nagar",
"Jabalpur",
"Jaipur",
"Jaisalmer",
"Jalandhar",
"Jalgaon",
"Jammu",
"Jamshedpur",
"Jejuri",
"Jhagadia",
"Jharsuguda",
"Jodhpur",
"Kagithapuram",
"Kaithal",
"Kakinada",
"Kalyan",
"Kalyani",
"Kanchipuram",
"Kangra",
"Kanhe",
"Kannur",
"Kanpur",
"Kapurthala",
"Karnal",
"Kasaragod",
"Katni",
"Kharsawan",
"Khatima",
"Khopoli",
"Khurda",
"Kochi",
"Kolar",
"Kolhapur",
"Kolkata",
"Kota",
"Kothur",
"Kozhikode",
"Krishnagiri",
"Kumrek",
"Kundaim",
"Kundli",
"Kurnool",
"Kushinagar",
"Kutch",
"Loni",
"Lucknow",
"Ludhiana",
"Madurai",
"Malanpur",
"Malappuram",
"Mandi",
"Mandideep",
"Manesar",
"Mangalore",
"Manipal",
"Maraimalai Nagar",
"Margao",
"Mathura",
"Medak",
"Meerut",
"Mewat",
"Miryalaguda",
"Moga",
"Mohali",
"Moradabad",
"Mumbai",
"Mundra",
"Munger",
"Muzaffar Nagar",
"Mysuru",
"Nagpur",
"Nainital",
"Nanjangud",
"Nashik",
"Navi Mumbai",
"Neemrana",
"Nellore",
"New Delhi",
"Newai",
"Noida",
"North 24 Parganas",
"Palakkad",
"Palghar",
"Panchmahal",
"Panipat",
"Pantnagar",
"Panvel",
"Paonta Sahib",
"Parwanoo",
"Pathankot",
"Patiala",
"Patna",
"Perundurai",
"Phulgaon",
"Pithampur",
"Ponda",
"Prayagraj",
"Puducherry",
"Pune",
"Raigad",
"Raigarh",
"Raipur",
"Raisen",
"Rajahmundry",
"Rajkot",
"Rajpura",
"Ramagundam",
"Ranchi",
"Ranga Reddy",
"Rayagada",
"Rewari",
"Rohtak",
"Roorkee",
"Rourkela",
"Rudrapur",
"S.A.S. Nagar",
"Saharanpur",
"Salem",
"Samalkha",
"Sangareddy",
"Sardarshahr",
"Satara",
"Satna",
"Secunderabad",
"Shahjahanpur",
"Shaktinagar",
"Shirur",
"Sikar",
"Siliguri",
"Silvassa",
"Sirmaur",
"Sirsa",
"Sitarganj",
"Sivakasi",
"Solan",
"Solapur",
"Sonipat",
"Sricity",
"Srinagar",
"Sriperumbudur",
"Surat",
"Surendranagar",
"Talegaon",
"Taloja",
"Tapi",
"Tezpur",
"Thiruvallur",
"Thiruvananthapuram",
"Tinsukia",
"Tiruchirappalli",
"Tirunelveli",
"Tiruvannamalai",
"Tokobari",
"Tughlakabad",
"Tumakuru",
"Udaipur",
"Udham Singh Nagar",
"Udupi",
"Ulhasnagar",
"Umerkoi",
"Una",
"Vadodara",
"Valsad",
"Vapi",
"Varanasi",
"Vasai",
"Vasco Da Gama",
"Vasind",
"Verna",
"Vijayawada",
"Virudhunagar",
"Visakhapatnam",
"Vrindavan",
"Waluj",
"Zaheerabad",
"Zirakpur",
"Halol",
"Hooghly",
"Jhajjar",
"Kanpur Nagar",
"Kathua",
"Khanna",
"Ramanagara",
"Rohad",
"Sahibabad",
"Sanand",
"Tada",
"Tehri Garhwal",
"Thane",
"Changsari",
"Charampa",
"Howrah",
"Chakan",
"Lapanga",
"Mammigatti",
"Mehsana",
"Bokaro",
"Dhenkanal",
"Gandhinagar",
"Haldia",
"Haveli",
"Jajpur",
"Krishnapuram",
"Maheshwaram",
"Malur",
"Santhpur",
"Thirutheri R.F.",
"Vellore",
"Vidyanagar",
"Yadadri",
"Curtorim",
"Dahanu",
"Mangal",
"Palwal",
]